chat text decoration
EinfachGustaf/SMPv2 pull request #3
Opened 2024-06-21 13:44 UTC by DinoMarlir

2024-06-25 18:03 UTC, mathearbeit76 commented on build.gradle.kts
> -    include(implementation("org.jetbrains.kotlinx", "kotlinx-serialization-json", "1.7.0"))
why?

2024-06-25 18:05 UTC, mathearbeit76 requested changes

2024-06-25 18:05 UTC, mathearbeit76 commented on src/main/java/live/einfachgustaf/mods/smp/mixins/MixinPlayerChatMessage.java
> +        live.einfachgustaf.mods.smp.mixinkt.MixinPlayerChatMessage.INSTANCE.injectDecoratedContent(cir);
consider importing the class

2024-06-25 18:05 UTC, mathearbeit76 commented on src/main/kotlin/live/einfachgustaf/mods/smp/mixinkt/MixinPlayerChatMessage.kt
> +object MixinPlayerChatMessage {
avoid duplicate class names please

2024-06-25 18:05 UTC, mathearbeit76 commented on build.gradle.kts
> -    include(implementation("org.jetbrains.kotlinx", "kotlinx-serialization-json", "1.7.0"))
also, consider using one format of dependency notations and not multiple across the buildscript

2025-01-03 22:50 UTC, DasSharkk commented
Bump this pr, as it is done now

2025-01-03 22:51 UTC, DinoMarlir commented on src/main/kotlin/live/einfachgustaf/mods/smp/mixinkt/PlayerChatMessageHook.kt
> +    fun convertAdventureToMinecraft(adventureComponent: AdventureComponent, provider: HolderLookup.Provider): MutableComponent? {
Please create extension functions like Component#nativeComponent()

2025-01-03 23:02 UTC, DinoMarlir reviewed
Thank you for your contribution!

2025-01-03 23:04 UTC, DasSharkk commented
fixes #2

2025-01-03 23:04 UTC, merged