Status Feature
EinfachGustaf/SMPv2 pull request #4
Opened 2024-06-21 15:30 UTC by DinoMarlir

2024-06-25 18:11 UTC, mathearbeit76 requested changes

2024-06-25 18:11 UTC, mathearbeit76 commented on src/main/resources/smp.mixins.json
> +    "feature.status.MixinServerPlayer"
Please don't  register server side mixins on the common side

2024-06-25 18:11 UTC, mathearbeit76 commented on src/main/kotlin/live/einfachgustaf/mods/smp/utils/Global.kt
> +    prettyPrint = true
you may want to add `isLenient = true`

2024-06-25 18:11 UTC, mathearbeit76 commented on src/main/kotlin/live/einfachgustaf/mods/smp/features/Status.kt
> +        logger.info("LOL CALLED")
Either make it a `logger.debug()` or remove it

2024-06-25 18:11 UTC, mathearbeit76 commented on src/main/kotlin/live/einfachgustaf/mods/smp/features/Status.kt
> +                statusList.filter { !it.name.contains(" ") }.map { it.name }
Why? Just set the argument to `StringArgumentType.greedyString()` in order to deal with spaces

2024-06-25 18:11 UTC, mathearbeit76 commented on src/main/kotlin/live/einfachgustaf/mods/smp/features/Status.kt
> +            source.sendSystemMessage(Component.literal("Your status is now '${statusArgument()}'.")) // TODO: translateable
Please consider using the same component builder in all places.

2024-06-25 18:11 UTC, mathearbeit76 commented on src/main/kotlin/live/einfachgustaf/mods/smp/features/Status.kt
> +data class Status(
This could be a HashMap instead.

2024-06-25 18:12 UTC, mathearbeit76 commented
would be better to mark the PR as a draft

2024-07-04 21:20 UTC, DinoMarlir commented
> would be better to mark the PR as a draft

@mathearbeit76 yeah, thank you for your review, I have new ideas for a status system so I am going to recode that,

2025-07-20 19:16 UTC, closed without merging